- hosts: webservers
  gather_facts: no
  tasks:
    - name: Install git
      apt:
        name: git
        state: present
      become: yes
      when: ansible_os_family == 'Debian'
      tags: install_git

    - name: update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'
      tags: update_cache
      become: yes

    - name: copy .gitconfig to the user home difrectory for every user
      template:
        src: ../templates/.gitconfig
        dest: "/home/{{ item }}/.gitconfig"
      loop: "{{ users }}"
      become: yes
      tags: git
