- hosts: webservers
  vars:
    nginx_port: 80
    root_dir: /usr/share/nginx/html
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: present
      become: yes

    - name: copy '../files/index.html' to '/usr/share/nginx/html/index.html'
      copy:
        src: ../files/index.html
        dest: "{{ root_dir }}/index.html"
      become: yes

    - name: copy '../templates/nginx.conf' to '/etc/nginx/nginx.conf'
      template:
        src: ../templates/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      become: yes

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: reloaded
      become: yes

