- hosts: webservers
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: present
      when: ansible_os_family == 'Debian'
      become: yes

    - name: install cowsay
      apt:
        name: cowsay
        state: present
      when: ansible_os_family == 'Debian'
      become: yes

    - name: cowsay 'Hello, from web server' and register ans cowanswer
      command: cowsay 'Hello, from web server'
      register: cowsay_out
      when: ansible_os_family == 'Debian'
      become: yes
      tags: ["cowsay", "copy_html"]

    - name: copy '../files/index.html' to '/usr/share/nginx/html/index.html'
      template:
        src: ../files/index.html
        dest: "{{ root_dir }}/index.html"
      when: ansible_os_family == 'Debian'
      tags: copy_html
      become: yes

    - name: copy '../templates/nginx.conf' to '/etc/nginx/nginx.conf'
      template:
        src: ../templates/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      when: ansible_os_family == 'Debian'  # only debigan, because centos hasn't nginx folder
      become: yes

    - name: create users from the 'users' variable loop
      user:
        name: "{{ item }}"
        home: "/home/{{ item }}"
        state: present
      loop: "{{ users }}"  #
      become: yes
      tags: create_users

    - name: echo ansible_host
      debug:
          msg: " http://{{ ansible_host }}/ "
      become: yes
      tags: debug

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: reloaded
      become: yes

