- hosts: webservers
  gather_facts: no
  
  tasks:
    - name: uninstall git
      apt:
        name: git
        state: absent
      become: yes

    - name: delete gitconfig files for every user
      file:
          path: "/home/{{ item }}/.gitconfig"
          state: absent
      loop: "{{ users }}"
      become: yes